### ISSUE TITLE
https://solliancenet.github.io/microsoft-learning-path-build-copilots-with-cosmos-db-labs/python/instructions/05-sdk-queries.html

### ISSUE THREAD

**Issue by israeloros** [solliancenet/microsoft-learning-path-build-copilots-with-cosmos-db#11]
Code fails because the authentication mechanism is using credentials and the documentation does not provide any instructions on how to set up permissions on the Azure Cosmos DB account.

 (venv) PS C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\05-sdk-queries> python script.py
 Traceback (most recent call last):
   File "C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\05-sdk-queries\script.py", line 27, in <module>
     asyncio.run(main())
   File "C:\Users\israeloros\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
     return runner.run(main)
            ^^^^^^^^^^^^^^^^
   File "C:\Users\israeloros\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
     return self._loop.run_until_complete(task)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\israeloros\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 686, in run_until_complete  
     return future.result()
            ^^^^^^^^^^^^^^^
   File "C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\05-sdk-queries\script.py", line 11, in main
     async with CosmosClient(endpoint, credential=credential) as client:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\venv\Lib\site-packages\azure\cosmos\aio\_cosmos_client.py", line 198, in __aenter__
     await self.client_connection._setup()
   File "C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\venv\Lib\site-packages\azure\cosmos\aio\_cosmos_client_connection_async.py", line 292, in _setup
     database_account = await self._global_endpoint_manager._GetDatabaseAccount(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\venv\Lib\site-packages\azure\cosmos\aio\_global_endpoint_manager_async.py", line 121, in _GetDatabaseAccount  
     database_account = await self._GetDatabaseAccountStub(self.DefaultEndpoint, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\venv\Lib\site-packages\azure\cosmos\aio\_global_endpoint_manager_async.py", line 147, in _GetDatabaseAccountStub
     return await self.client.GetDatabaseAccount(endpoint, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\venv\Lib\site-packages\azure\cosmos\aio\_cosmos_client_connection_async.py", line 410, in GetDatabaseAccount  
     result, self.last_response_headers = await self.__Get("", request_params, headers, **kwargs)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\venv\Lib\site-packages\azure\cosmos\aio\_cosmos_client_connection_async.py", line 1198, in __Get
     return await asynchronous_request.AsynchronousRequest(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\venv\Lib\site-packages\azure\cosmos\aio\_asynchronous_request.py", line 172, in AsynchronousRequest
     return await _retry_utility_async.ExecuteAsync(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\venv\Lib\site-packages\azure\cosmos\aio\_retry_utility_async.py", line 96, in ExecuteAsync
     result = await ExecuteFunctionAsync(function, global_endpoint_manager, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\venv\Lib\site-packages\azure\cosmos\aio\_retry_utility_async.py", line 200, in ExecuteFunctionAsync
     return await function(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\israeloros\Documents\Learning\Azure\CosmosDB\Labs\cosmosdb-copilot\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\venv\Lib\site-packages\azure\cosmos\aio\_asynchronous_request.py", line 123, in _Request
     raise exceptions.CosmosHttpResponseError(message=data, response=response)
 azure.cosmos.exceptions.CosmosHttpResponseError: (Forbidden) Request blocked by Auth fsi-rag-demo : Request is blocked because principal [210d07f6-9a65-465d-a4f6-26fd15a35adf] does not have required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/readMetadata] on resource [/]. Learn more: https://aka.ms/cosmos-native-rbac.
 ActivityId: efe10161-4a7d-40a5-8deb-97f8d6234ecf, Microsoft.Azure.Documents.Common/2.14.0
 Code: Forbidden
 Message: Request blocked by Auth fsi-rag-demo : Request is blocked because principal [210d07f6-9a65-465d-a4f6-26fd15a35adf] does not have required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/readMetadata] on resource [/]. Learn more: https://aka.ms/cosmos-native-rbac.
 ActivityId: efe10161-4a7d-40a5-8deb-97f8d6234ecf, Microsoft.Azure.Documents.Common/2.14.0
 Unclosed client session
 client_session: <aiohttp.client.ClientSession object at 0x000002BB15BA3B00>
 Unclosed client session
 client_session: <aiohttp.client.ClientSession object at 0x000002BB15BA3830>
 Unclosed connector
 connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x000002BB15F3B050>, 91590.875)])']
 connector: <aiohttp.connector.TCPConnector object at 0x000002BB15BA3890>
 
 Recommendation to change the following lines:
 
 1)
  endpoint = "<cosmos-endpoint>"
  credential = DefaultAzureCredential()
 
  async def main():
      async with CosmosClient(endpoint, credential=credential) as client:
  
 to:
 
  endpoint = "<cosmos-endpoint>"
  key="<cosmos-account-key>"
 
  async def main():
      async with CosmosClient(endpoint, key) as client:
      
2) Include instructions to use az login before running the script and also grant data plane RBAC permissions to the principal running the script as follows:

   az cosmosdb sql role assignment create \
   --account-name "<cosmos-account>" \
   --resource-group "<resource-group>" \
   --scope "/" \
   --principal-id "<principal-object-id>" \
   --subscription "<subscription-name>" \
   --role-definition-id "00000000-0000-0000-0000-000000000002" 

This last comment also applies to https://solliancenet.github.io/microsoft-learning-path-build-copilots-with-cosmos-db-labs/python/instructions/06-sdk-pagination.html

**Comment by joelhulen** [comment]
All labs refer to these common instructions, which include setting up RBAC permissions: <https://solliancenet.github.io/microsoft-learning-path-build-copilots-with-cosmos-db-labs/common/instructions/00-setup-cosmos-db.html>

You'll see a link to these instructions under the **Create an Azure Cosmos DB for NoSQL account** header (https://solliancenet.github.io/microsoft-learning-path-build-copilots-with-cosmos-db-labs/python/instructions/05-sdk-queries.html#create-an-azure-cosmos-db-for-nosql-account), plus all exercises in the learning modules refer to these setup instructions for the user to follow before completing the lab.
