### ISSUE TITLE
Python SDK labs	07 - Generate vector embeddings with Azure OpenAI and store them in Azure Cosmos DB for NoSQL - Test the Embedding Step 8

### ISSUE THREAD

**Issue by fenyan-msft** [solliancenet/microsoft-learning-path-build-copilots-with-cosmos-db#19]
At step 8, I am getting this error:

Traceback (most recent call last):
  File "C:\Users\fenyan\source\repos\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\07-build-copilot\.venv\Lib\site-packages\azure\core\pipeline\transport\__init__.py", line 90, in __getattr__
    from ._aiohttp import AioHttpTransport
  File "C:\Users\fenyan\source\repos\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\07-build-copilot\.venv\Lib\site-packages\azure\core\pipeline\transport\_aiohttp.py", line 45, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\fenyan\source\repos\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\07-build-copilot\api\app\main.py", line 10, in <module>
    credential = DefaultAzureCredential()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fenyan\source\repos\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\07-build-copilot\.venv\Lib\site-packages\azure\identity\aio\_credentials\default.py", line 154, in __init__
    ManagedIdentityCredential(
  File "C:\Users\fenyan\source\repos\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\07-build-copilot\.venv\Lib\site-packages\azure\identity\aio\_credentials\managed_identity.py", line 106, in __init__
    self._credential = ImdsCredential(client_id=client_id, identity_config=identity_config, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fenyan\source\repos\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\07-build-copilot\.venv\Lib\site-packages\azure\identity\aio\_credentials\imds.py", line 23, in __init__
    self._client = AsyncManagedIdentityClient(_get_request, **dict(PIPELINE_SETTINGS, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fenyan\source\repos\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\07-build-copilot\.venv\Lib\site-packages\azure\identity\_internal\managed_identity_client.py", line 40, in __init__
    self._pipeline = self._build_pipeline(**kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fenyan\source\repos\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\07-build-copilot\.venv\Lib\site-packages\azure\identity\aio\_internal\managed_identity_client.py", line 39, in _build_pipeline
    return build_async_pipeline(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fenyan\source\repos\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\07-build-copilot\.venv\Lib\site-packages\azure\identity\_internal\pipeline.py", line 88, in build_async_pipeline
    from azure.core.pipeline.transport import (  # pylint: disable=non-abstract-transport-import, no-name-in-module
  File "C:\Users\fenyan\source\repos\microsoft-learning-path-build-copilots-with-cosmos-db-labs\python\07-build-copilot\.venv\Lib\site-packages\azure\core\pipeline\transport\__init__.py", line 94, in __getattr__
    raise ImportError("aiohttp package is not installed") from err
ImportError: aiohttp package is not installed

**Comment by joelhulen** [comment]
I've updated the requirements file to include the `aiohttp` and other missing packages.
